### ISSUE TITLE
LTex keeps running after VS Code has quit

### ISSUE THREAD

**Issue by SamuelMarks** [valentjn/vscode-ltex#872]
**Describe the bug**
File -> Exit. Check `ps` and find `java` is still running an hour later.

**Steps to reproduce**

1. Open VS code (I tend to have ~3 windows each with a LaTeX document)
2. Exit VS code
3. Check processes

**Expected behavior**
Should exit when VS code is exited

**Sample document**
N/A

**LTeX configuration**

No custom config

**"LTeX Language Server" log file**
First, reproduce the bug. Then, go to `View` → `Output` and select `LTeX Language Server` in the drop-down list. Paste this log here:

<details>

```
REPLACE_THIS_WITH_LTEX_LANGUAGE_SERVER_LOG
```

</details>

**"LTeX Language Client" log file**
First, set the `ltex.trace.server` setting in your `settings.json` to `"verbose"`. Then, reload the VS Code window and reproduce the bug. Go to `View` → `Output` and select `LTeX Language Client` in the drop-down list. Paste this log here (note: it will contain your checked document):

<details>

```
REPLACE_THIS_WITH_LTEX_LANGUAGE_CLIENT_LOG
```

</details>

**Version information**
List here the version information of the relevant software.

- Operating system: Linux (Ubuntu 23.10 with 6.7.7 kernel)
- VS Code: 
1.87.0
019f4d1419fbc8219a181fab7892ebccf7ee29a2
x64- vscode-ltex: x.xx
- ltex-ls: x.xx (only if not using ltex-ls automatically downloaded by LTeX)
- Java: openjdk version "19.0.2" 2023-01-17

**Additional context/information**
You can add any other context or information about the problem here.

**Comment by wc1018** [comment]
I have the same problem as you. Openjdk  binary eats my RAM repeatedly every time I start VSCode. Has it been solved now?

**Comment by pierrebrd** [comment]
Same problem, still no fix ?

**Comment by reneas** [comment]
It seems this repo is not longer maintained. There is, however, a fork where I opened another Issue -> [here](https://github.com/neo-ltex/vscode-ltex/issues/89)

**Comment by seangtkelley** [comment]
Still occurring as of Jul 2025. Unfortunately [neo-ltex](https://github.com/neo-ltex/vscode-ltex) seems to also no longer be maintained. [ltex+](https://github.com/ltex-plus/vscode-ltex-plus) might be the only similar option. Other spell check extensions are available like [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).
